export type Locale = 'zh' | 'en'
export type AccessMode = 'lowVision' | 'oneHand' | 'quiet'

export interface SiteCopy {
  skipLink: string
  brandDescriptor: string
  navigation: {
    demo: string
    stack: string
    github: string
    languageLabel: string
    languageName: string
  }
  hero: {
    title: string
    titleLabel: string
    lead: string
    primaryAction: string
    flow: string
  }
  demo: {
    title: string
    panelLabel: string
    panelDescription: string
    generatedLabel: string
    modesLabel: string
    modes: Record<AccessMode, string>
    taskLabel: string
    task: string
    taskDetail: string
    stepLabel: string
    stepTitle: string
    stepDetail: string
    action: string
    completed: string
    reset: string
    disclosure: string
  }
  technology: {
    title: string
    layers: Array<{
      title: string
      meta: string
    }>
    safety: string
  }
  footer: {
    line: string
    disclaimer: string
  }
}

export const siteCopy = {
  zh: {
    skipLink: '跳到主要内容',
    brandDescriptor: '界面翻译器',
    navigation: {
      demo: '演示',
      stack: '技术栈',
      github: 'GitHub',
      languageLabel: '切换语言',
      languageName: 'EN',
    },
    hero: {
      title: '为眼前的设备，\n生成更好用的界面。',
      titleLabel: '为眼前的设备，生成更好用的界面。',
      lead: '扫描面板。Relay 生成适合你和当前任务的界面。',
      primaryAction: '看演示',
      flow: '扫描 · 确认 · 生成',
    },
    demo: {
      title: '同一台机器，为你改变。',
      panelLabel: '扫描',
      panelDescription: '一块有 12 个圆形按键和 23 分钟显示屏的面板；第 8 个按键已高亮。',
      generatedLabel: 'Relay 生成',
      modesLabel: '选择辅助模式',
      modes: {
        lowVision: '低视力',
        oneHand: '单手',
        quiet: '静音',
      },
      taskLabel: '任务',
      task: '快速洗',
      taskDetail: '23 分钟 · 冷水',
      stepLabel: '第 1 步，共 3 步',
      stepTitle: '按下右侧高亮按钮',
      stepDetail: '触觉指引位置，相机确认结果。',
      action: '开始引导',
      completed: '这一步已确认',
      reset: '重新演示',
      disclosure: '原型演示。操作前请确认设备标签与状态。',
    },
    technology: {
      title: 'Native 保持可信，GenUI 负责变化。',
      layers: [
        { title: 'Native', meta: 'iOS · Android' },
        { title: 'Lynx', meta: 'ReactLynx runtime' },
        { title: 'OpenUI', meta: '受控组件目录' },
        { title: 'Agent', meta: 'Vision · SSE · Guardrails' },
      ],
      safety: '权限、确认与关键操作始终由 Native 执行。',
    },
    footer: {
      line: 'Relay · Accessible GenUI',
      disclaimer: '黑客松原型，不用于医疗诊断或无人监督的设备控制。',
    },
  },
  en: {
    skipLink: 'Skip to main content',
    brandDescriptor: 'Interface Translator',
    navigation: {
      demo: 'Demo',
      stack: 'Stack',
      github: 'GitHub',
      languageLabel: 'Switch language',
      languageName: '中文',
    },
    hero: {
      title: 'A better interface for\nwhat’s in front of you.',
      titleLabel: 'A better interface for what’s in front of you.',
      lead: 'Scan a panel. Relay generates an interface for you and the task at hand.',
      primaryAction: 'See demo',
      flow: 'Scan · Confirm · Generate',
    },
    demo: {
      title: 'The same machine, changed for you.',
      panelLabel: 'Scan',
      panelDescription:
        'A panel with 12 round controls and a 23-minute display. Control 8 is highlighted.',
      generatedLabel: 'Generated by Relay',
      modesLabel: 'Choose an access mode',
      modes: {
        lowVision: 'Low vision',
        oneHand: 'One hand',
        quiet: 'Quiet',
      },
      taskLabel: 'Task',
      task: 'Quick wash',
      taskDetail: '23 minutes · Cold water',
      stepLabel: 'Step 1 of 3',
      stepTitle: 'Press the highlighted button on the right',
      stepDetail: 'Haptics guide your hand. The camera confirms the result.',
      action: 'Start guidance',
      completed: 'Step confirmed',
      reset: 'Replay demo',
      disclosure: 'Prototype. Confirm the device labels and state before acting.',
    },
    technology: {
      title: 'Native stays trusted. GenUI handles change.',
      layers: [
        { title: 'Native', meta: 'iOS · Android' },
        { title: 'Lynx', meta: 'ReactLynx runtime' },
        { title: 'OpenUI', meta: 'Controlled component catalog' },
        { title: 'Agent', meta: 'Vision · SSE · Guardrails' },
      ],
      safety: 'Permissions, confirmations, and critical actions always run in Native.',
    },
    footer: {
      line: 'Relay · Accessible GenUI',
      disclaimer: 'Hackathon prototype. Not for medical diagnosis or unsupervised device control.',
    },
  },
} satisfies Record<Locale, SiteCopy>
