source 'https://cdn.cocoapods.org/'

platform :ios, '17.0'

install! 'cocoapods', :deterministic_uuids => false

target 'Relay' do
  use_frameworks! :linkage => :static

  pod 'Lynx', '3.8.0', :subspecs => ['Framework']
  pod 'PrimJS', '3.8.0', :subspecs => ['quickjs', 'napi']
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end

    # Lynx 3.8 adds -Werror per source file. Xcode 26 reports deprecated UIKit
    # APIs in that third-party code, which should remain warnings for the host.
    next unless target.name == 'Lynx'

    target.source_build_phase.files.each do |build_file|
      flags = build_file.settings&.fetch('COMPILER_FLAGS', nil)
      next unless flags

      build_file.settings['COMPILER_FLAGS'] = flags
        .split
        .reject { |flag| flag == '-Werror' }
        .join(' ')
    end
  end
end
